log4j.rootLogger=info,console,partner

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yyyyMMdd HH\:mm\:ss.SSS} | %-5p | %c.%L | %M() | %m%n

log4j.appender.partner=org.apache.log4j.DailyRollingFileAppender
log4j.appender.partner.layout=org.apache.log4j.PatternLayout
log4j.appender.partner.file=C://error.log
log4j.appender.partner.DatePattern='.'yyyy-MM-dd
log4j.appender.partner.layout.ConversionPattern=%d{yyyyMMdd HH\:mm\:ss.SSS} | %-5p |%T| %c{1}.%L | %M | %m%n